/* eslint-disable prettier/prettier */
export const items = [
  {
    id: 1,
    category: 'Jeans',
    productName: 'Marine Straight Fit Jeans',
    productPrice: 3090,
    originalPrice: 4490,
    description: 'HIGH-WAIST JEANS WITH FIVE POCKETS. STRAIGHT-LONG-LEG DESIGN. FRONT ZIP FLY AND BUTTON FASTENING.',
    isOff: true,
    offPercentage: 31,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Pants/p1/p1img3.webp'),
    productImageList: [
      require('../database/productImg/Pants/p1/p1img1.webp'),
      require('../database/productImg/Pants/p1/p1img2.webp'),
      require('../database/productImg/Pants/p1/p1img3.webp'),
    ]
  },
  {
    id: 2,
    category: 'Jeans',
    productName: 'Flared Jeans',
    productPrice: 3090,
    originalPrice: 4490,
    description: 'CLASSIC FIGURE-HUGGING FIT THAT OPENS IN TO A FLARED LEG FROM THE KNEE.',
    isOff: true,
    offPercentage: 31,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Pants/p2/p2img1.webp'),
    productImageList: [
      require('../database/productImg/Pants/p2/p2img1.webp'),
      require('../database/productImg/Pants/p2/p2img2.webp'),
      require('../database/productImg/Pants/p2/p2img3.webp'),
    ]
  },
  {
    id: 3,
    category: 'Jeans',
    productName: 'Slim Fit Flare Jeans',
    productPrice: 2490,
    originalPrice: 4990,
    description: 'SNUG FITTING JEAN WHICH TAPERS DOWN FROM THE HIPS. DESIGNED TO DELIVER STYLE, COMFORT AND VERSATILITY.',
    isOff: true,
    offPercentage: 50,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Pants/p3/p3img1.webp'),
    productImageList: [
      require('../database/productImg/Pants/p3/p3img1.webp'),
      require('../database/productImg/Pants/p3/p3img2.webp'),
      require('../database/productImg/Pants/p3/p3img3.webp'),
    ]
  },
  {
    id: 4,
    category: 'Jeans',
    productName: 'Wide Baggy Fit Jeans',
    productPrice: 3090,
    originalPrice: 4490,
    description: 'IT IS MID-RISE WITH A CONTOURED WAIST & CONSISTS OF A RELAXED LEG FROM THE THIGH TO THE KNEE WHICH CUTS WIDE THROUGHOUT THE LEG.',
    isOff: true,
    offPercentage: 31,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Pants/p4/p4img1.webp'),
    productImageList: [
      require('../database/productImg/Pants/p4/p4img1.webp'),
      require('../database/productImg/Pants/p4/p4img2.webp'),
      require('../database/productImg/Pants/p4/p4img3.webp'),
    ]
  },
  {
    id: 5,
    category: 'Jeans',
    productName: 'Rigid Slim Fit Jeans',
    productPrice: 1990,
    originalPrice: 3990,
    description: 'SNUG FITTING JEAN WHICH TAPERS DOWN FROM THE HIPS. DESIGNED TO DELIVER STYLE, COMFORT AND VERSATILITY.',
    isOff: true,
    offPercentage: 50,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Pants/p5/p5img1.webp'),
    productImageList: [
      require('../database/productImg/Pants/p5/p5img1.webp'),
      require('../database/productImg/Pants/p5/p5img2.webp'),
      require('../database/productImg/Pants/p5/p5img3.webp'),
    ]
  },
  {
    id: 6,
    category: 'Jeans',
    productName: ' Slim Fit Non Ripped Jeans',
    productPrice: 2250,
    originalPrice: 4490,
    description: 'SNUG FITTING JEAN WHICH TAPERS DOWN FROM THE HIPS. DESIGNED TO DELIVER STYLE, COMFORT AND VERSATILITY.',
    isOff: true,
    offPercentage: 49,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Jeans/p6/p6img1.webp'),
    productImageList: [
      require('../database/productImg/Jeans/p6/p6img1.webp'),
      require('../database/productImg/Jeans/p6/p6img2.webp'),
      require('../database/productImg/Jeans/p6/p6img3.webp'),
    ]
  },
  {
    id: 7,
    category: 'Jeans',
    productName: 'Loose Fit Jogger Jeans',
    productPrice: 2190,
    originaPrice: 4490,
    description: 'IT IS MID-RISE WITH A CONTOURED WAIST & CONSISTS OF A RELAXED LEG FROM THE THIGH TO THE KNEE WHICH CUTS WIDE THROUGHOUT THE LEG',
    isOff: true,
    offPercentage: 51,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Jeans/p7/p7img1.webp'),
    productImageList: [
      require('../database/productImg/Jeans/p7/p7img1.webp'),
      require('../database/productImg/Jeans/p7/p7img2.webp'),
      require('../database/productImg/Jeans/p7/p7img3.webp'),
    ]
  },
  {
    id: 8,
    category: 'Jeans',
    productName: 'Slim Fit And Patched Jeans',
    productPrice: 2190,
    originaPrice: 4490,
    description: 'THE MODERN FITCUTS CLOSER TO THE BODY, DEFINING YOUR BODY SILHOUETTE. SLIMS DOWN THROUGH THE CHEST AND SHOULDER OFFERING A CLEAN NEAT LOOK.',
    isOff: true,
    offPercentage: 51,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Jeans/p8/p8img1.webp'),
    productImageList: [
      require('../database/productImg/Jeans/p8/p8img1.webp'),
      require('../database/productImg/Jeans/p8/p8img2.webp'),
      require('../database/productImg/Jeans/p8/p8img3.webp'),
    ]
  },
  {
    id: 9,
    category: 'Jeans',
    productName: 'Skinny Fit Jeans With Spots And Frayed HEM',
    productPrice: 1990,
    originaPrice: 3990,
    description: 'IT IS MID-RISE WITH A CONTOURED WAIST & CONSISTS OF A RELAXED LEG FROM THE THIGH TO THE KNEE WHICH CUTS WIDE THROUGHOUT THE LEG',
    isOff: true,
    offPercentage: 50,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Jeans/p9/p9img1.webp'),
    productImageList: [
      require('../database/productImg/Jeans/p9/p9img1.webp'),
      require('../database/productImg/Jeans/p9/p9img2.webp'),
      require('../database/productImg/Jeans/p9/p9img3.webp'),
    ]
  },
  {
    id: 10,
    category: 'Jeans',
    productName: 'Slim Fit Jeans',
    productPrice: 2250,
    originaPrice: 4490,
    description: 'IT IS MID-RISE WITH A CONTOURED WAIST & CONSISTS OF A RELAXED LEG FROM THE THIGH TO THE KNEE WHICH CUTS WIDE THROUGHOUT THE LEG',
    isOff: true,
    offPercentage: 49,
    isAvailable: true,
    quantity: '1',
    productImage: require('../database/productImg/Jeans/p10/p10img1.webp'),
    productImageList: [
      require('../database/productImg/Jeans/p10/p10img1.webp'),
      require('../database/productImg/Jeans/p10/p10img2.webp'),
      require('../database/productImg/Jeans/p10/p10img3.webp'),
    ]
  },
]